### ISSUE TITLE
Posição do footer

### ISSUE THREAD

**Issue by PauloCamargos** [italogsfernandes/imagens-medicas-2#55]
Footer posicionado no meio da página.

**Comment by italogsfernandes** [comment]
resolvido

**Comment by italogsfernandes** [comment]
çkasmfas

**Comment by italogsfernandes** [comment]
sefd

**Comment by PauloCamargos** [comment]
![image](https://user-images.githubusercontent.com/19214203/66442919-5c941e80-ea13-11e9-8bec-9dc3e2e71a00.png)
Não resolveu não.

**Comment by italogsfernandes** [comment]
spdfldskflçkds

**Comment by PauloCamargos** [comment]
Resolvido
